#1.2.0-SNAPSHOT
#Thu Jan 07 16:02:22 IST 2021
mosip.reg.healthcheck.url=http\://10.10.20.220/v1/authmanager/actuator/health
mosip.reg.rollback.path=../BackUp
mosip.reg.cerpath=/cer//mosip_cer.cer
mosip.reg.db.key=bW9zaXAxMjM0NQ\=\=
mosip.reg.xml.file.url=http\://10.10.20.220/registration-client/maven-metadata.xml
mosip.reg.app.key=bBQX230Wskq6XpoZ1c+Ep1D+znxfT89NxLQ7P4KFkc4\=
mosip.reg.client.tpm.availability=Y
mosip.reg.env=qa
mosip.reg.dbpath=db/reg
mosip.reg.logpath=../logs
mosip.reg.mdm.server.port=8080
mosip.reg.version=1.2.0-SNAPSHOT
mosip.reg.packetstorepath=../PacketStore
mosip.reg.client.url=http\://10.10.20.220/registration-client/
